### ISSUE TITLE
Plugin doesn't work correctly on glpi10

### ISSUE THREAD

**Issue by trisosamu** [UB-Mannheim/glpi-wol#2]
Must rename plugin folder from glpi-wol-0.0.2 to wakeonlan

**Comment by stweil** [comment]
Did you install with git (as described in the README), or did you download the source code?

**Comment by trisosamu** [comment]
Hi I've tried both installation.
when activate plugin and go to configuration, debug mode tell me this: "Uncaught Exception ArgumentCountError: Too few arguments to function PluginWakeonlanConfig::showForm(), 0 passed in /var/www/html/glpi/marketplace/wakeonlan/front/config.php on line 39 and at least 1 expected in /var/www/html/glpi/marketplace/wakeonlan/inc/config.class.php at line 53"

**Comment by dennmuel** [comment]
Hi @trisosamu 
I just pushed a [possible fix](https://github.com/UB-Mannheim/glpi-wol/commit/fcfd58440d63f97ee7b6d9c2b1c5b407c36d304e). Could please try it and get back to us if it works or not?

**Comment by trisosamu** [comment]
Something it appened.
![wakeonlan](https://user-images.githubusercontent.com/78987040/200810059-a8a1f66b-dde2-445a-9d78-fc72158c2851.PNG)

**Comment by dennmuel** [comment]
Thanks for your quick reply. I haven't been able to properly reproduce this, but I just pushed some code that I think might fix those warnings. Could you please try again?

**Comment by trisosamu** [comment]
Okay, now I dont't see any error. I try to send wol signal but pc doesn't start.
If I use this command "wakeonlan xx:xx:xx:xx:xx:xx" from my glpi shell it works.
What could be the problem?

pc and glpi are on the same network.
I need to configure wol plugin or I leave blank?

**Comment by dennmuel** [comment]
Thanks for your feedback. Glad to hear the warnings are gone. I'll make a new release for these fixes. Thank you for reporting!

Regarding your separate problem:
If the server GLPI is running on also sends the magic packets (and not a remote server), it should suffice to check "local" in the plugin config. This is working in our instance. Is there any error message after you send the Wake on LAN action?

By "glpi shell" you mean the command line interface of the GLPI server's operating system? If that's working but not via the plugin, I could imagine two possible causes: Either the machine you try to wake has an IPv6 address (the plugin currently only works with IPv4). Or the GLPI database is incomplete or obsolete. You could check whether your database contains all data needed by the [get_netinfo()](https://github.com/UB-Mannheim/glpi-wol/blob/d5c2fbd2a0061e90458925b9dfc579b33a54854f/inc/wol.class.php#L31) function and whether it is up to date (for example you could still have an old ip address in GLPI that does not match the real one).

**Comment by trisosamu** [comment]
thank you, wol signal doesn't send because on some computer there are IPV4 and IPV6. If I delete IPV6, signal sends correctly.
Do you think we will wakeup only with mac address ?

**Comment by dennmuel** [comment]
Do you mean deleting/disabling ipv6 on the target machine or deleting the ipv6 entry in the GLPI database? The latter would be a little weird since the ipv6 address shouldn't play any role for [it is completely ignored](https://github.com/UB-Mannheim/glpi-wol/blob/1ce7cb84bff6afc59bae639a9ca56172ebe40c68/inc/wol.class.php#L67). As long as there is a valid ipv4 entry it should work just the same.

I think the underlying problem is that the code is still too much tailored towards our specific environment. We do WoL on a remote server (expecting a broadcast address) for ipv4 targets only. It would be desirable to refactor the code so that it
- does not need a broadcast but any ip address (including broadcasts)
- supports ipv6
- could skip the ip if host and target are in the same subnet

I suggest to address this in a different issue.

As an **_untested workaround_**, you could try modifying `get_netinfo()` so as to
- get rid of all the netmask stuff in the [db query](https://github.com/UB-Mannheim/glpi-wol/blob/1ce7cb84bff6afc59bae639a9ca56172ebe40c68/inc/wol.class.php#L33)
- remove [this line](https://github.com/UB-Mannheim/glpi-wol/blob/1ce7cb84bff6afc59bae639a9ca56172ebe40c68/inc/wol.class.php#L67) to include v6 addresses
- replace [these lines](https://github.com/UB-Mannheim/glpi-wol/blob/1ce7cb84bff6afc59bae639a9ca56172ebe40c68/inc/wol.class.php#L74-L79) with something like the following to effectively use the target's ipv6 address in `$netinfo['broad']`.

```
if (filter_var($netinfo['name'], FILTER_VALIDATE_IP)) {
   $netinfo['broad'] = $netinfo['name'];
}

if (filter_var($netinfo['mac'], FILTER_VALIDATE_MAC)) {
   array_push($result, $netinfo);
}
```

That should effectively try WoL with the mac and ipv6 address of the target.

**Comment by dennmuel** [comment]
Hi @trisosamu,
I haven't heard from you in two weeks, so I'd like to close this issue assuming it is no longer relevant. Feel free to reopen, if I'm mistaken.

As said, I'd like to address the underlying issues with IPv6 etc. in a separate issue #3 as soon as I find the time. PRs are of course always welcome. :)
